### ISSUE TITLE
Rename this repository (e.g. `rocker-org.github.io`)

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/website#36]
It is better to follow the general naming rule for repository names for the organization's website.
For example: https://github.com/docker/docker.github.io

Reference: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites

**Comment by cboettig** [comment]
iirc, using the special org-style name has implications on how websites work that are hosted on other GH repos (i.e. if we wanted websites with separate domain names under the same org -- though not sure why we would ever want that).  Also, I always felt like that naming convention was needlessly opaque to causal contributors; feels a little more like a historical hack from the early days of GH-Pages. But happy to go with the change, since it is the common convention and the repo description field probably makes this clear enough.  Just wanted to mention these thoughts for discussion first.

**Comment by eddelbuettel** [comment]
Agreed, and I also seem to recall that the proposed name is mostly a GH convention when you do not have control over your own domain and rely on $USER.github.io (and/or do it because you like github.io URLs).  May not be as pressing an issue for us as we own the domain and can use CNAME (which GitHub supports nicely) for sub-domains if we ever needed it.

**Comment by eddelbuettel** [comment]
I personally find those long names unwieldy.  It's also not needed.  These days for example www.rcpp.org runs off a repo rcpp-website which is in my name (and even private) and not even in the RcppCore org on GitHub.  "It's just DNS" and a file `CNAME` with the external URL (for us: www.rocker-project.org).

But you are the one doing all the work so I am not going to stand in your way.  Do as you see fit, I personally would not.

**Comment by eitsupi** [comment]
@cboettig Could you take a look at setting of custom domain `www.rocker-project.org` for GitHub pages?
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by cboettig** [comment]
I've mapped the apex domain (`https://rocker-project.org`) to the four IP addresses and added https://github.com/rocker-org/website/blob/gh-pages/CNAME, this seems to work.

I haven't gotten the subdomain to resolve.  I have set:

![image](https://user-images.githubusercontent.com/222586/179319364-8a50e098-b5c3-40eb-a10d-7d47ae0e6083.png)

but the subdomain isn't happy with this:

![image](https://user-images.githubusercontent.com/222586/179319430-3364c706-8366-4fb8-aa6e-99dca2242a42.png)


Not sure what I'm missing here.  (last time I set one of these up was a few years ago but don't remember having any issues with CNAME and subdomains....)

**Comment by eddelbuettel** [comment]
Those parts are gnarly.  Maybe rcpp.org is a model?  We use to have more subdomains, now it may only be gallery.rcpp.org (also at github) so the main responds to both https://rcpp.org and https://www.rcpp.org -- and just maps the latter to the former.

I have a similar set of A records, but then only CNAME entries for used (and old unused) entries.  gallerie goes via CNAME into JJ's github.ui, www goes into mine.  Along with that I have a web-redirect for http(s)://rcpp.org to go to www.rcpp.org.  

That way the 'global' looking domain itself is really just a map to the CNAMEd actual site in www.rcpp.org.

**Comment by eitsupi** [comment]
Thanks for doing this!
It seems the redirect working well, but DNS checking hasn't been finished?

![image](https://user-images.githubusercontent.com/50911393/179394657-2402d866-992e-4a37-a6f1-003679636f11.png)

**Comment by cboettig** [comment]
@eitsupi Thanks, the DNS seems to have settled down and  `www.rocker-project.org` is now resolving as expected.  (Also looks like GitHub doesn't like having an ALIAS set for the subdomain only a CNAME).  Top-level domain is still ok too.

**Comment by eitsupi** [comment]
The checking has been finished!
Thank you for your trial and error on this.

![image](https://user-images.githubusercontent.com/50911393/181050635-f42830fd-953f-4da5-abf0-4ec02af92d46.png)

**Comment by eddelbuettel** [comment]
That it the weirdest thing but yay!   I will admit to having changed my setups sooner 'to go to green'.

Nice work, all!

**Comment by eitsupi** [comment]
For now, it does not seem necessary to do this, so close it.
